import Head from "next/head";
import Header from "../components/Header";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App hulu 2.0 </title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* Header */}
			<Header />
			{/* Nav */}
			{/* Results */}
		</div>
	);
}
